## Satuin File di Folder dataset

In [34]:
import glob
 
# list all csv files only
# csv_files = glob.glob('*.{}'.format('csv'))
# csv_files

# Specify the folder or directory path
folder_path = "../1 Scraping/Dataset"

# Find all text files in the specified folder and its subdirectories
csv_files = glob.glob(folder_path + "/*.csv")
csv_files

['../1 Scraping/Dataset\\banjir_tweets.csv',
 '../1 Scraping/Dataset\\erupsi_tweets.csv',
 '../1 Scraping/Dataset\\gempa_tweets.csv',
 '../1 Scraping/Dataset\\longsor_tweets.csv',
 '../1 Scraping/Dataset\\puting beliung_tweets.csv',
 '../1 Scraping/Dataset\\tsunami_tweets.csv']

In [35]:
import pandas as pd
 
df_csv_append = pd.DataFrame()

#Append files
for file in csv_files:
    df = pd.read_csv(file)
    # Remove the "Unnamed: 0" column if present
    if "Unnamed: 0" in df.columns:
        df.drop("Unnamed: 0", axis=1, inplace=True)
    df_csv_append = df_csv_append.append(df, ignore_index=True)

df_csv_append

C:\Users\arkan\AppData\Local\Temp\ipykernel_12956\2341229342.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_csv_append = df_csv_append.append(df, ignore_index=True)
C:\Users\arkan\AppData\Local\Temp\ipykernel_12956\2341229342.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_csv_append = df_csv_append.append(df, ignore_index=True)
C:\Users\arkan\AppData\Local\Temp\ipykernel_12956\2341229342.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_csv_append = df_csv_append.append(df, ignore_index=True)
C:\Users\arkan\AppData\Local\Temp\ipykernel_12956\2341229342.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_csv_append = df_csv_append.append(df, ignore_index=True)
C:\Users\arkan\AppData\Local\Temp\ipykernel_12956\2341229342.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_csv_append = df_csv_append.append(df, ignore_index=True)
C:\Users\arkan\AppData\Local\Temp\ipykernel_12956\2341229342.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_csv_append = df_csv_append.append(df, ignore_index=True)

,Date,User,Tweet
0,2023-02-27 08:51:51+00:00,atcumuchan,akhirny naik gojek w malas banjir banjiran
1,2023-02-27 08:49:05+00:00,dargut10,Banjir luar dalam
2,2023-02-27 08:48:23+00:00,tennisieee,bismillah banjir congrats
3,2023-02-27 08:44:33+00:00,chezeechoco,huaa naek kreta ekonomi berjamjam super tegak ...
4,2023-02-27 08:44:12+00:00,gabriccia1,"kata teman uwe,\nhari ini di laman jual beli O..."
...,...,...,...
29995,2022-10-10 02:38:10+00:00,atiegrace,lepas subuh tidur balik. mimpi pasal tsunami.t...
29996,2022-10-10 01:52:04+00:00,luqysm,makk pengin ganti frame tsunami
29997,2022-10-10 01:25:55+00:00,RSipirock,"Bencana terbesar suatu bangsa bkn lah Tsunami,..."
29998,2022-10-10 00:26:47+00:00,KoFPLI_JOG,"Tips main FPL musim ini, pasang winger kiri mu..."
29999,2022-10-09 20:43:56+00:00,lYuliaRiyantil,BMKG menyampaikan tak ada potensi tsunami usai...

In [36]:
df_csv_append.to_csv('scraped_tweets.csv')

## Rapiin column

In [37]:
import pandas as pd
df = pd.read_csv('scraped_tweets.csv')

In [38]:
df

,Unnamed: 0,Date,User,Tweet
0,0,2023-02-27 08:51:51+00:00,atcumuchan,akhirny naik gojek w malas banjir banjiran
1,1,2023-02-27 08:49:05+00:00,dargut10,Banjir luar dalam
2,2,2023-02-27 08:48:23+00:00,tennisieee,bismillah banjir congrats
3,3,2023-02-27 08:44:33+00:00,chezeechoco,huaa naek kreta ekonomi berjamjam super tegak ...
4,4,2023-02-27 08:44:12+00:00,gabriccia1,"kata teman uwe,\nhari ini di laman jual beli O..."
...,...,...,...,...
29995,29995,2022-10-10 02:38:10+00:00,atiegrace,lepas subuh tidur balik. mimpi pasal tsunami.t...
29996,29996,2022-10-10 01:52:04+00:00,luqysm,makk pengin ganti frame tsunami
29997,29997,2022-10-10 01:25:55+00:00,RSipirock,"Bencana terbesar suatu bangsa bkn lah Tsunami,..."
29998,29998,2022-10-10 00:26:47+00:00,KoFPLI_JOG,"Tips main FPL musim ini, pasang winger kiri mu..."
29999,29999,2022-10-09 20:43:56+00:00,lYuliaRiyantil,BMKG menyampaikan tak ada potensi tsunami usai...

In [39]:
df.drop('Unnamed: 0', inplace=True, axis=1)

In [40]:
df = df.drop(columns=['Date', 'User'])
df

                                                   Tweet
0             akhirny naik gojek w malas banjir banjiran
1                                      Banjir luar dalam
2                              bismillah banjir congrats
3      huaa naek kreta ekonomi berjamjam super tegak ...
4      kata teman uwe,\nhari ini di laman jual beli O...
...                                                  ...
29995  lepas subuh tidur balik. mimpi pasal tsunami.t...
29996                    makk pengin ganti frame tsunami
29997  Bencana terbesar suatu bangsa bkn lah Tsunami,...
29998  Tips main FPL musim ini, pasang winger kiri mu...
29999  BMKG menyampaikan tak ada potensi tsunami usai...

[30000 rows x 1 columns]

In [43]:
df.to_csv('tweet_only.csv', index=False)