In [1]:
import pandas as pd

In [2]:
test_df  = pd.read_csv('../The/test.csv')
train_df = pd.read_csv('../The/train.csv')
train_unlabelled_df = pd.read_csv('../The/train_unlabelled.csv', index_col = [0])

In [4]:
test_df

,id,text,Label
0,1316740974190630126,titisan air mata kini kekeringan,0
1,1316740974190631210,tni polri serta satpol pp dki menyambangi loka...,0
2,1355811699857604608,"Gempa Mag:5.2, 31-Jan-21 16:28:55 WIB, Lok:5....",1
3,1316740974190629802,berbagai klaster penyebaran covid 19 kita moni...,0
4,1316740974190629578,saya tetap optimistis perekonomian indonesia a...,0
...,...,...,...
1810,1399501905450081915,Volume kubah lava di sektor barat daya sebesar...,1
1811,1316740974190630708,kelar wfh udah minta ganti tuh laptop,0
1812,1316740974190631274,waktu gempa di bali baru baru ini sebelumnya a...,0
1813,163491606069121024,Angin Puting Beliung Rusak Puluhan Rumah di Ma...,1
1814,1316740974190631236,padahal penajam jg pernah banjir bnyk tuh di b...,0

In [5]:
test_df.query("Label == 1")

,id,text,Label
2,1355811699857604608,"Gempa Mag:5.2, 31-Jan-21 16:28:55 WIB, Lok:5....",1
6,1386707478025445381,"Gempa Mag:3.1, 26-Apr-21 20:56:57 WIB, Lok:7....",1
9,1399501905450081985,"3. Tanggal 26 Januari 2021 pukul 19:46 WIB, aw...",1
13,1255864247155699714,"Banjir di Kab. Aceh Tenggara, Prov. Aceh (25/4...",1
14,1399501905450081762,Awanpanas guguran Merapi tanggal 2 Juni 2021 p...,1
...,...,...,...
1800,1334592942145634304,"Gempa Mag:5.4, 04-Des-20 02:48:40 WIB, Lok:3....",1
1806,668072195516555265,Gerbang Tol Cikunir 2 Roboh Kena Angin Puting ...,1
1807,1308055246464147457,Pusat Pengendali Operasi (Pusdalops) BNPB memo...,1
1810,1399501905450081915,Volume kubah lava di sektor barat daya sebesar...,1
1813,163491606069121024,Angin Puting Beliung Rusak Puluhan Rumah di Ma...,1

In [ ]:
import pandas as pd

# Load the datasets
df1 = pd.read_csv('banjir.csv')
df2 = pd.read_csv('longsor.csv')
df3 = pd.read_csv('tsunami.csv')
df4 = pd.read_csv('gempa.csv')
df5 = pd.read_csv('erupsi.csv')
df6 = pd.read_csv('pueting_beliung.csv')

# Combine the datasets using concat
combined_df = pd.concat([df1, df2, df3, df4, df5, df6], axis=0)

# Reset the index of the combined DataFrame
combined_df = combined_df.reset_index(drop=True)

combined_df.to_csv('scraped_tweets.csv', index=False)